[package]
name = "wagon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
logos-derive = "0.13.0"
petgraph = {version = "0.6.3", default-features = false}
wagon-macros = { path = "./wagon-macros"}
logos-display = "0.1.2"
ordered-float = "3.9.1"
quote = "1.0.33"
proc-macro2 = "1.0.67"
indexmap = "2.0.2"
cached = "0.46.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
